language: rust
os:
- linux
- osx
rust:
  - stable
cache: cargo
addons:
  apt:
    packages:
    - libsdl2-dev
    - libasound2-dev
script:
- cargo test --verbose --all
- cargo build --verbose --all --release
- ls -al
- cp target/release/onair-sonoff onair-sonoff-${TRAVIS_OS_NAME}
deploy:
- provider: releases
  name: onair-sonoff-${TRAVIS_BRANCH}
  skip_cleanup: true
  api_key:
    secure: V22krxFDko4J2IjEdcvTVpSaMoBp4o/Do5E8tg5sFO/02MF7nnydY5Hr6T7QjADlOZWjXP0BfP1FHlSTHxAkR5y3OHL8+vyb3T1HUJ9YEKaiPkqtZJtQ0900GXpUssLbwOE54ZzfWBQPCCvzRPE6n/Oib37ZPTKQq0xA0FD19HSXt+vj1HXKv6M5Sydijx1lxe9nqjV5Wd2C+/aFZiSR2jBu7ssXGZx9QCWdoePv9lTF9+OPivaz9pCJjyBZtLw1wvp+IzB4PKV0xoRsWyTH1gkJPwEnVEX1qPDcCtkZ97e4mRxx1vfhKp40TITMySUqn9k5MgV3T7Q+yFbQD223T9fDRSUsGYNsi2QPbZA98EYTM/VN7kyyx71vFHak6cHCl4Qgce6AtzTjx0Z3AR5zd2u67cpY/s+TAjbL7kFcyKVj4V3LU3RGxyT5vt3KYiStOH91oybZNRXBOegzaI2KyBdPxZbEwLRDyPLGSHxdCHW+EdL1z1iak6ebRfc351+/sLCYYmmTM1+aWA/dKqc9vEQ4arOH2gYJZnJv+wP4AKFy8p6PbCUeETd4S5oYdqPGDXXpdrs2iEnjMk5LzRrnZADD/RjJjanvP6/s/dNraPYmaadWDzrfx0YLIiZzQGEFNXPiXow0YSRNquaEH/ly2A+OjbdFyJvspJ/VYqqH61M=
  file_glob: true
  file:
  - onair-sonoff-linux
  on:
    condition: $TRAVIS_OS_NAME = linux
    repo: armyofevilrobots/onair-sonoff
    tags: true
- provider: releases
  name: onair-sonoff-${TRAVIS_BRANCH}
  skip_cleanup: true
  api_key:
    secure: V22krxFDko4J2IjEdcvTVpSaMoBp4o/Do5E8tg5sFO/02MF7nnydY5Hr6T7QjADlOZWjXP0BfP1FHlSTHxAkR5y3OHL8+vyb3T1HUJ9YEKaiPkqtZJtQ0900GXpUssLbwOE54ZzfWBQPCCvzRPE6n/Oib37ZPTKQq0xA0FD19HSXt+vj1HXKv6M5Sydijx1lxe9nqjV5Wd2C+/aFZiSR2jBu7ssXGZx9QCWdoePv9lTF9+OPivaz9pCJjyBZtLw1wvp+IzB4PKV0xoRsWyTH1gkJPwEnVEX1qPDcCtkZ97e4mRxx1vfhKp40TITMySUqn9k5MgV3T7Q+yFbQD223T9fDRSUsGYNsi2QPbZA98EYTM/VN7kyyx71vFHak6cHCl4Qgce6AtzTjx0Z3AR5zd2u67cpY/s+TAjbL7kFcyKVj4V3LU3RGxyT5vt3KYiStOH91oybZNRXBOegzaI2KyBdPxZbEwLRDyPLGSHxdCHW+EdL1z1iak6ebRfc351+/sLCYYmmTM1+aWA/dKqc9vEQ4arOH2gYJZnJv+wP4AKFy8p6PbCUeETd4S5oYdqPGDXXpdrs2iEnjMk5LzRrnZADD/RjJjanvP6/s/dNraPYmaadWDzrfx0YLIiZzQGEFNXPiXow0YSRNquaEH/ly2A+OjbdFyJvspJ/VYqqH61M=
  file_glob: true
  file:
  - onair-sonoff-osx
  on:
    condition: $TRAVIS_OS_NAME = osx
    repo: armyofevilrobots/onair-sonoff
    tags: true
